---
title: "Comed_daily_pred"
author: "Natasha Nath"
date: "December 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading packages and data
```{r}
library(tidyverse) 

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

```{r}
library(ggplot2)
library(lubridate)
library(reshape2)
library(zoo)
library(mctest)
library(tidyverse)
require(data.table)
```

```{r}
comed_hourly <- read.csv('./hourly-energy-consumption/COMED_hourly.csv', header=TRUE)
comed_hourly$Datetime <-  as.POSIXct(comed_hourly$Datetime,format ='%m/%d/%Y %H:%M')

#tidyr::fill(comed_hourly, direction = "down")
comed_hourly <- comed_hourly %>% map(na.locf)

comed_hourly <- as.data.frame(comed_hourly)

comed_hourly <- comed_hourly[comed_hourly$Datetime >= '2013-01-01 00:00:00' & comed_hourly$Datetime <= '2017-01-31 23:00:00',]

comed_daily <- comed_hourly
comed_daily <- comed_daily %>% mutate(Date = as.Date(Datetime)) %>% select(-Datetime)

comed_daily <- comed_daily %>% group_by(Date) %>% dplyr::summarise(day_comsump = sum(COMED_MW))
#comed_daily <- comed_daily %>% filter(Date < '2017-01-01')
```

```{r}
suppressWarnings(library(tseries))
```

```{r}
datapath <- "C:/Users/Natasha/OneDrive/Courses/AUTUMN 2018/Time series/Assignments/Elec_Power_Consumption/historical-hourly-weather-data"

df_hum<-
  read.csv(file=paste(datapath,"humidity.csv",sep="/"),
           row.names=NULL,header=TRUE,sep=",")
df_hum<- df_hum[,c('datetime','Chicago')]

df_hum$datetime <- as.POSIXct(df_hum$datetime,format="%Y-%m-%d %H:%M:%S")

df_hum <- subset(df_hum, df_hum$datetime >= "2013-01-01 00:00:00" & df_hum$datetime <= "2017-01-31 23:00:00") 

colnames(df_hum)<-c('Date','Humidity')                  

df_pre<-
  read.csv(file=paste(datapath,"pressure.csv",sep="/"),
           row.names=NULL,header=TRUE,sep=",")

df_pre<- df_pre[,c('datetime','Chicago')]

df_pre$datetime <- as.POSIXct(df_pre$datetime,format="%Y-%m-%d %H:%M:%S")

df_pre <- subset(df_pre, df_pre$datetime >= "2013-01-01 00:00:00" & df_pre$datetime <= "2017-01-31 23:00:00") 

colnames(df_pre)<-c('Date','Pressure')  

df_temp<-
  read.csv(file=paste(datapath,"temperature.csv",sep="/"),
           row.names=NULL,header=TRUE,sep=",")

df_temp<- df_temp[,c('datetime','Chicago')]

df_temp$datetime <- as.POSIXct(df_temp$datetime,format="%Y-%m-%d %H:%M:%S")

df_temp <- subset(df_temp, df_temp$datetime >= "2013-01-01 00:00:00" & df_temp$datetime <= "2017-01-31 23:00:00") 

colnames(df_temp)<-c('Date','Temperature')  


df_wind_d<-
  read.csv(file=paste(datapath,"wind_direction.csv",sep="/"),
           row.names=NULL,header=TRUE,sep=",")

df_wind_d<- df_wind_d[,c('datetime','Chicago')]

df_wind_d$datetime <- as.POSIXct(df_wind_d$datetime,format="%Y-%m-%d %H:%M:%S")

df_wind_d <- subset(df_wind_d, df_wind_d$datetime >= "2013-01-01 00:00:00" & df_wind_d$datetime <= "2017-01-31 23:00:00") 

colnames(df_wind_d)<-c('Date','Wind_Direction') 

df_wind_s<-
  read.csv(file=paste(datapath,"wind_speed.csv",sep="/"),
           row.names=NULL,header=TRUE,sep=",")

df_wind_s<- df_wind_s[,c('datetime','Chicago')]

df_wind_s$datetime <- as.POSIXct(df_wind_s$datetime,format="%Y-%m-%d %H:%M:%S")

df_wind_s <- subset(df_wind_s, df_wind_s$datetime >= "2013-01-01 00:00:00" & df_wind_s$datetime <= "2017-01-31 23:00:00") 

colnames(df_wind_s)<-c('Date','Wind_Speed') 
```

```{r}
library(plyr)
df_weather_main<-join_all(list(df_hum,df_pre,df_temp,df_wind_d,df_wind_s), by='Date', type='full')

library(imputeTS)

Humidity1<-na.kalman(df_hum$Humidity)
Humidity1<-as.vector(Humidity1)

Pressure1<-na.kalman(df_pre$Pressure)
Pressure1<-as.vector(Pressure1)

Temperature1<-na.kalman(df_temp$Temperature)
Temperature1<-as.vector(Temperature1)


df_weather_main <- cbind(df_weather_main,Humidity1,Pressure1,Temperature1)

df_weather_main[,c('Humidity','Pressure','Temperature')] <- list(NULL)

sapply(df_weather_main, function(x) sum(is.na(x)))

df_weather_main <- df_weather_main %>% mutate(Date=as.Date(Date))

df_weather_daily <- df_weather_main %>% group_by(Date) %>% dplyr::summarise(Wind_Direction = mean(Wind_Direction),Wind_Speed =
                                                                       mean(Wind_Speed),Temperature1 = mean(Temperature1),
                                                                     Pressure1 = mean(Pressure1), Humidity1=mean(Humidity1))

#df_weather_daily <- df_weather_daily %>% filter(Date < '2017-01-01')
```

```{r}
data_daily <- comed_daily %>% join(df_weather_daily, by='Date')

data_daily <- data_daily[-c(1155, 1493), ] 
```

```{r}
Plot_CS <- ggplot(data_daily) + geom_line(mapping = aes(Date,day_comsump),colour="Blue") + ggtitle("Daily power consumption Vs Duration")

Plot_temp <-ggplot(data_daily) + geom_line(mapping = aes(Date,Temperature1),colour="Blue") + ggtitle("Temperature Vs Duration") 

Plot_hum <-ggplot(data_daily) + geom_line(mapping = aes(Date,Humidity1),colour="Blue") + ggtitle("Humidity Vs Duration") 

Plot_press <-ggplot(data_daily) + geom_line(mapping = aes(Date,Pressure1),colour="Blue") + ggtitle("Pressure Vs Duration") 

Plot_windspeed <-ggplot(data_daily) + geom_line(mapping = aes(Date,Wind_Speed),colour="Blue") + ggtitle("Wind Speed Vs Duration") 

plot_G  <- multiplot(Plot_CS,Plot_temp,Plot_hum, Plot_press, Plot_windspeed)
print(plot_G)


data_daily[2] <- lapply(data_daily[2], as.numeric)
data_corr <- data.matrix(data_daily[-1])
heatmap(data_daily[-1], scale="column", col = cm.colors(256))

heatmap(data_corr, Rowv=NA, Colv=NA, col = cm.colors(256), scale="column", margins=c(5,10))


cormat <- round(cor(data_corr),2)
head(cormat)

library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)

library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```

## Running a TBATS models as we have multiple seasonalities
```{r}
library(forecast)

data_daily %>% select(day_comsump, Date) %>% mstl() %>% autoplot() + xlab("Date")
```
## Splitting data into train and test
```{r}
train_df <-data_daily[1:1095,]
test_df <- data_daily[1096:1460,]
```

## Group data into weekly data
```{r}
data_weekly <- data_daily
data_weekly$seven_day_index <- c(0, rep(1:(nrow(data_weekly)-1)%/%7))
data_weekly <- data_weekly %>% group_by(seven_day_index) %>%
  dplyr::summarise(week_date = head(Date,1),
                   consump = sum(day_comsump),
                   temperature = mean(Temperature1),
                   pressure = mean(Pressure1),
                   humidity = mean(Humidity1),
                   wind_speed = mean(Wind_Speed),
                   wind_direction = mean(Wind_Direction)) %>% 
  select(-(seven_day_index))

write.csv(data_weekly, "data_weekly.csv", row.names = FALSE)
```

```{r}
daily_train_df <- data_daily[1:1338,]
daily_test_df <- data_daily[1339:1460,]

write.csv(data_daily, "data_daily.csv", row.names = FALSE)
```

## Prophet predictions
```{r}
library(prophet)
library(tidyverse)
library(tidyquant)

daily_df_train <- daily_train_df[,c('Date','day_comsump')]
daily_df_test <- daily_test_df[,c('Date','day_comsump')]

colnames(daily_df_train) <- c('ds','y')
fit_prophet <- prophet(daily_df_train, n.changepoints = 100, yearly.seasonality = TRUE, weekly.seasonality = TRUE)
future_comed <- daily_df_test 
colnames(future_comed) <- c('ds', 'day_consump')
f_prophet <- predict(fit_prophet,future_comed)
plot(fit_prophet,f_prophet)

f_prophet['actual_consump'] <- future_comed['day_consump']
# Plot residuals for predicted test data
f_prophet %>%
  mutate(resid = actual_consump - yhat) %>%
  ggplot(aes(x = ds, y = resid)) +
    geom_hline(yintercept = 0, color = "red") +
    geom_point(alpha = 0.5, color = palette_light()[[1]]) +
    geom_smooth() + theme_tq()

f_prophet %>%
  gather(x, y, actual_consump, yhat) %>%
  ggplot(aes(x = ds, y = y, color = x)) +
    geom_point(alpha = 0.5) +
    geom_line(alpha = 0.5) +
    scale_color_manual(values = palette_light()) +
    theme_tq()
```

Let's look at the series as decomposed by prophet:

```{r}
prophet_plot_components(fit_prophet,f_prophet)
```

make future predictions using prophet
```{r}
future <- make_future_dataframe(fit_prophet, periods = 122)
forecast <- predict(fit_prophet, future)
plot(fit_prophet, forecast) +
    theme_tq()
```

How does the model perform
```{r}
library(TSPred)
rmse <- function(actual, predicted){
  sqrt(mean((actual - predicted)^2))
}
mae <- function(actual,predicted)
{
    error <- actual - predicted
    mean(abs(error))
}

smape <- function(actual, predicted){
  sMAPE(actual, predicted)
}

sprintf("The RMSE of the prophet model is: %f",rmse(f_prophet$actual_consump, f_prophet$yhat))
sprintf("The MAE of the prophet model is: %f",mae(f_prophet$actual_consump, f_prophet$yhat))
sprintf("The sMAPE of the prophet model is: %f",smape(f_prophet$actual_consump, f_prophet$yhat))
```

## Run TBATS model

```{r}
msts_comed_power <- msts(daily_train_df$day_comsump, seasonal.periods = c(7,365), start = c(2013,01,01))

#TBATS MODEL
tbats_comed_power <- tbats(msts_comed_power) 
plot(tbats_comed_power)

f_comed_tbats <- forecast(tbats_comed_power, h = 122)
autoplot(f_comed_tbats) +ggtitle('Comed Daily Power - Forecast, 2016')+ xlab('Date') + ylab('Consumption in MW')
tbats_score_daily <- accuracy(f_comed_tbats,daily_test_df$day_comsump)

tbats_score[2,]

checkresiduals(f_comed_tbats)
```

## Calculate error metrics for LSTM
```{r}
suppressPackageStartupMessages(library(reticulate))
np <- import("numpy")

actual <- np$load("actual_daily.npy")
predicted <- np$load("predicted_daily.npy")

sprintf("The RMSE of the LSTM model is: %f",rmse(actual, predicted))
sprintf("The MAE of the LSTM model is: %f",mae(actual, predicted))
sprintf("The sMAPE of the LSTM model is: %f",smape(actual, predicted))
```
